config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms

  root 'rooms#index'

  get 'search', to: 'rooms#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  
  has_many :messages
  has_many :users, through: :messages
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller


end

app/controllers/clearance/passwords_controller.rb
require 'active_support/deprecation'

class Clearance::PasswordsController < Clearance::BaseController
  before_action :ensure_existing_user, only: [:edit, :update]
  before_action :ensure_email_present, only: [:create]
  skip_before_action :require_login, only: [:create, :edit, :new, :update], raise: false

  def new
    render template: "passwords/new"
  end

  def create
    if user = find_user_for_create
      user.forgot_password!
      deliver_email(user)
    end

    render template: "passwords/create"
  end

  def search
    @users = User.all
    render template: 'search'
  end

  def edit
    @user = find_user_for_edit

    if params[:token]
      session[:password_reset_token] = params[:token]
      redirect_to url_for
    else
      render template: "passwords/edit"
    end
  end

  def update
    @user = find_user_for_update

    if @user.update_password(password_from_password_reset_params)
      sign_in @user
      redirect_to url_after_update
      session[:password_reset_token] = nil
    else
      flash_failure_after_update
      render template: "passwords/edit"
    end
  end

  private

  def deliver_email(user)
    ::ClearanceMailer.change_password(user).deliver_now
  end

  def password_from_password_reset_params
    params.dig(:password_reset, :password)
  end

  def find_user_by_id_and_confirmation_token
    user_param = Clearance.configuration.user_id_parameter
    token = params[:token] || session[:password_reset_token]

    Clearance.configuration.user_model.
      find_by(id: params[user_param], confirmation_token: token.to_s)
  end

  def email_from_password_params
    params.dig(:password, :email)
  end

  def find_user_for_create
    Clearance.configuration.user_model.
      find_by_normalized_email(email_from_password_params)
  end

  def find_user_for_edit
    find_user_by_id_and_confirmation_token
  end

  def find_user_for_update
    find_user_by_id_and_confirmation_token
  end

  def ensure_email_present
    if email_from_password_params.blank?
      flash_failure_when_missing_email
      render template: "passwords/new"
    end
  end

  def ensure_existing_user
    unless find_user_by_id_and_confirmation_token
      flash_failure_when_forbidden
      render template: "passwords/new"
    end
  end

  def flash_failure_when_forbidden
    flash.now[:alert] = translate(:forbidden,
      scope: [:clearance, :controllers, :passwords],
      default: t("flashes.failure_when_forbidden"))
  end

  def flash_failure_after_update
    flash.now[:alert] = translate(:blank_password,
      scope: [:clearance, :controllers, :passwords],
      default: t("flashes.failure_after_update"))
  end

  def flash_failure_when_missing_email
    flash.now[:alert] = translate(:missing_email,
      scope: [:clearance, :controllers, :passwords],
      default: t("flashes.failure_when_missing_email"))
  end

  def url_after_update
    Clearance.configuration.redirect_url
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    rooming = Room.find(message_params[:room_id])
    if rooming.columndialogue
      if not rooming.users.exists?(current_user.id)
        naming = rooming.name
        @message = Message.new(message_params)
        @message.user = User.find_by(email: naming)
        @message.save
      end
    end
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save

    SendMessageJob.perform_later(@message)
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id, :room_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @users = User.all
  end

  def search
    @rooms = Room.all
    @users = User.all
    render 'search'
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @rooms = Room.all
    @users = User.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.slug = slug()
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      @room_params ||= params.require(:room).permit(:name, :columndialogue)
    end
end

def slug
  while true
    @slug = SecureRandom.hex(10) 
    if not Room.exists? slug: @slug
      break
    end
  end
  return @slug
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    def index
      @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/admin.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<section>
    <div class="d-flex align-items-center justify-content-center" style="height: 700px">
        <div class="container-fluid"> 
            <div id="clearance" class="sign-in">
                <div class="col-md-6 offset-md-3">
                    <div class="shadow-lg p-3 mb-5 bg-white rounded">
                        <div class="row justify-content-md-center">
                            
                            <div id="clearance" class="sign-up">
                                <br>
                                <h2><%= t(".Sign up") %></h2>
                                <br>
                                <%= form_for @user do |form| %>
                                    <div class="text-field">
                                    <%= form.label :email %>
                                    <%= form.text_field :email, class: 'form-control', type: 'email' %>
                                  </div>
                                  <br>
                                  <div class="password-field">
                                    <%= form.label :password %>
                                    <%= form.password_field :password, class: 'form-control' %>
                                  </div>
                                
                                <br>
                                <div class="submit-field">
                                    <%= form.submit class: "btn btn-primary btn-block" %>
                                </div>

                                <div class="other-links">
                                    <%= link_to t(".sign_in"), sign_in_path %>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section>
      <%= yield %>
    </section>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/my_passwords_layout.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<section>
    <div class="d-flex align-items-center justify-content-center" style="height: 700px">
        <div class="container-fluid"> 
            <div id="clearance" class="sign-in">
                <div class="col-md-6 offset-md-3">
                    <div class="shadow-lg p-3 mb-5 bg-white rounded">
                        <div class="row justify-content-md-center">
                            <div id="clearance" class="password-reset">
                            <h2><%= t(".Reset password") %></h2>
                        
                            <p><%= t(".Reset your password using the form below: specify your email.") %></p>
                        
                            <%= form_for :password, url: passwords_path do |form| %>
                            <div class="text-field">
                                <%= form.label :email %>
                                <%= form.text_field :email, type: 'email', class: 'form-control' %>
                            </div>
                            <br>
                            <div class="submit-field">
                                <%= form.submit class: "btn btn-primary btn-block" %>
                            </div>
                            <% end %>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/session.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<section>
    <div class="d-flex align-items-center justify-content-center" style="height: 700px">
        <div class="container-fluid"> 
            <div id="clearance" class="sign-in">
                <div class="col-md-6 offset-md-3">
                    <div class="shadow-lg p-3 mb-5 bg-white rounded">
                        <div class="row justify-content-md-center">
                            <%= form_for :session, url: session_path do |form| %>
                                <br>
                                <h1>Sign in</h1>
                                <br>
                                <div class="text-field">
                                    <%= form.label :email %>
                                    <%= form.text_field :email, class: 'form-control', type: 'email' %>
                                </div>
                                <br>
                                <div class="password-field">
                                    <%= form.label :password %>
                                    <%= form.password_field :password, class: 'form-control' %>
                                </div>
                                <br>
                                <div class="submit-field">
                                    <%= form.submit class: "btn btn-primary btn-block" %>
                                </div>
                                <div class="other-links">
                                    <div class="left-linked">
                                        <% if Clearance.configuration.allow_sign_up? %>
                                            <%= link_to t(".sign_up"), sign_up_path %>
                                        <% end %>
                                    </div>
                                    <div class="right-linked">
                                        <%= link_to t(".forgot_password"), new_password_path %>
                                    </div>
                                </div>
                                <br>
                                <br>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/messages/_form.html.erb
<%= form_for(message, remote: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :room_id, value: room.id %>
  <div class="input-group">
    <%= form.text_area :content, placeholder: "Type your message here...", class: 'form-control', style: "height:45px;resize:none;", required: true %>
    <div class="input-group-append">

      <script>
      function myFunction() {
        const element = document.getElementById("silent");
        element.scrollIntoView();
      }
      </script>
      
      <%= form.submit "Send", onclick: "myFunction()", class: "btn btn-primary", id: "chat-btn" %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="row">
  <div class="message mb-2 <%= 'me' if message.user == current_user %>">
    <div class="content-container">
    
      <div class="content">
        <% message.content.split("\n").each do |par| %>
          <%= par %><br>
        <% end %>
      </div>

      <div class="author">
        <%= message.user.email %> 
      </div>
      <%# message.created_at could be added as well%> 
    </div>
  </div>
</div>

<%# message.content.split("\n").each do |par| %>
<%# end %>

app/views/messages/_mine.html.erb
<div class="row">
  <div class="message mb-2 me">
    <div class="content-container">
      <div class="content">
        <%= message.content.gsub(/[\r\n]+/, '<br>').html_safe %>
      </div>
      <div class="author">
        <%= message.user.email %>
      </div>
    </div>
  </div>
</div>

app/views/messages/_theirs.html.erb
<div class="row">
  <div class="message mb-2">
    <div class="content-container">
      <div class="content">
        <%= message.content.gsub(/[\r\n]+/, '<br>').html_safe %>
      </div>
      <div class="author">
        <%= message.user.email %>
      </div>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
var chatBtn = document.getElementById("chat-btn");
chatBtn.disabled = false;

var chatBox = document.getElementById("message_content");
chatBox.value = '';

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.user_id %></td>
        <td><%= message.room_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @message.room_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Add a new room" %>
    <%= form.check_box :columndialogue, style: "visibility: hidden;" %>
    <%= form.text_field :name, class: 'form-control', required: true, placeholder: "Room name" %>
  </div>

  <%= form.submit "Add", id: "room-btn", class: "btn btn-outline-primary btn-block" %>
<% end %>

app/views/rooms/_search.html.erb
<button id="modal-btn" class="btn btn-outline-secondary btn-block" disabled>Search</button>
<div id="popup-modal" class="modal">
  <div class="modal-content">
    <span class="close" style="padding-left: 97%;padding-top: 4px;">&times;</span>
    <div class="text-center" style="color: black;"><h1>Search</h1></div>
    <div class="modal-body">
      <br>
      <p style="padding-left: 30px;">Here you can search for users and start a chat:</p>
      <%= render 'search_form', room: Room.new %>
    </div>
  </div>
</div>
<script>
var modal = document.getElementById("popup-modal");
var btn = document.getElementById("modal-btn");
var span = document.getElementsByClassName("close")[0];
document.addEventListener('readystatechange', event => { 
  if (new URLSearchParams(window.location.search).get('callFunction') === 'specialFunction') {
    modal.style.display = "block";
  }
});
span.onclick = function() {
  window.location.replace('/');
}
window.onclick = function(event) {
  if (event.target == modal) {
    window.location.replace('/');
  }
}
</script>

app/views/rooms/_search_form.html.erb
<br>
<input type="search" class="form-control" id="mySearch" onkeyup="myFunction()" style='width:500px; margin-left: 30px;' placeholder="Search.." title="Type in a category"><br>
    <ul class="a" id="myUL">
        <% @users.each do |user| %>
            <% if user.id != current_user.id %>
                <li class="text-muted" style="padding-left: 30px; margin-right: 30px"><p id="searched-user" onClick="reply_click(this.id)"><%= user.email %></p></li>
            <% end %>
        <% end %>
    </ul>
<%= form_with(model: room, local: true) do |form| %>
    <br>      
    <%= form.check_box :columndialogue, checked: "checked", style: "visibility: hidden;" %>  
    <%= form.text_field :name, class: 'form-control', id: "submit-string", style: "background-color: #cfcfcf;", required: true, placeholder: "User name" %>
    <br>
    <%= form.submit "Start a chat!", id: "room-btn", class: "btn btn-lg btn-primary btn-block", style: "background-color: #ff9800; color: white;" %>
    <br>
    <br>
<% end %>
<script>
function myFunction() {
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById("mySearch");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("p")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
    
window.onload = guidGenerator(); 
    function func() {
          return (((1+Math.random())*0x10000)|0).toString(16).substring(1);
        }
    function guidGenerator() {
        var yourElement = document.querySelectorAll('[id=searched-user]');
        for (let i = 0; i < yourElement.length; i++) {
        var S4 = func()
        yourElement[i].setAttribute("id", S4);
        console.log(S4)
        }
       }
       
           function reply_click(clicked_id)
    {
        var x = document.getElementById("submit-string");
        var submitButId = clicked_id;
        var link = document.getElementById(submitButId);
        var text = link.innerHTML;
        console.log(text)
        x.setAttribute("value", text);
    }
    </script>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<% if signed_in? %>
  <div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>
  <div id="user-id" data-user-id="<%= current_user.id %>"></div>
<% end %>
<% if signed_in? %>
      <div id="left">
        <div class="chat-room2">
          <div class="card no-outline">
            <div class="card-body2">
                Signed in as: <%= current_user.email %>
                <br>
                <br>
                <%= button_to 'Sign out', sign_out_path, id: "room-btn", class: "btn btn-outline-primary btn-block", method: :delete %>
              <div id="flash">
                <% flash.each do |key, value| %>
                  <div class="flash <%= key %>"><%= value %></div>
                <% end %>
              </div>
            </div>
          </div>
          <hr>
          <script>
          function redirectFunction() {
            window.location.replace('/search?callFunction=specialFunction');
          }
          </script>
          <button onclick="redirectFunction()" id="searcher" class="btn btn-outline-secondary btn-block">Search</button>
          <hr>
          <%= render 'form', room: Room.new %>
          <hr>
          <% @rooms.each do |room| %>
            <% if room.users.exists?(current_user.id) %>
              <% if room.columndialogue %>
                <%= link_to room, class: 'room-link' do %>
                  <% active_class = (@room == room) ? 'active' : '' %>
                    <div class="card no-outline mb-2 room-card <%= active_class %>">
                      <div class="card-body">
                        <% room.users.where.not(id: current_user.id).uniq.each do |other_user| %>
                          <span class='name'><%= other_user.email %></span><br>
                        <% end %>
                        <span class='member-count'>
                          <small><%= room.users.uniq.count %> Members</small>
                        </span>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                <%= link_to room, class: 'room-link' do %>
                  <% active_class = (@room == room) ? 'active' : '' %>
                    <div class="card no-outline mb-2 room-card <%= active_class %>">
                      <div class="card-body">
                        <span class='name'><%= room.name %></span><br>
                        <span class='member-count'>
                          <small><%= room.users.uniq.count %> Members</small>
                        </span>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <br>
          <br>
        </div>
      </div>
      <div id="right">
        <% if @room.present? %>
          <a class="members" href="#"><%= @room.users.uniq.count %> Members</a>
          <div class="chat-room">
            <nav class="navbar navbar-light">
              <% if @room.columndialogue %>
                <% if @room.users.exists?(current_user.id) %>
                  <span class="navbar-brand" href="#">
                    <% @room.users.where.not(id: current_user.id).uniq.each do |other_user| %>
                      <b><%= other_user.email %></b>
                    <% end %>
                  </span>
                <% else %>
                  <% if @room.users.uniq.count === 0 %>
                    <span class="navbar-brand" href="#">
                      <b><%= @room.name %></b>
                    </span>
                  <% else %>
                    <br>
                    <br>
                  <% end %>
                <% end %>
              <% else %>
                <span class="navbar-brand" href="#">
                  <b><%= @room.name %></b>
                </span>
              <% end %>
            </nav>
            <br>
            <div class="column">
              <div id="messages">
                <% if @room.columndialogue %>
                  <% if @room.users.exists?(current_user.id) %>
                    <% @room.messages.offset(1).each do |message| %>
                      <%= render 'messages/message', message: message %>
                    <% end %>
                  <% else %>
                    <% if @room.users.uniq.count === 0 %>
                      <% @room.messages.offset(1).each do |message| %>
                        <%= render 'messages/message', message: message %>
                      <% end %>
                    <% else %>
                      <div class="card border-danger mb-3" style="margin-left:30px; margin-right:10px; background-color:#fdd7e4;">
                        <div class="card-header">Error</div>
                        <div class="card-body text-danger">
                          <h5 class="card-title">Access denied</h5>
                          <p class="card-text">This is a private chat. You're not an authorized user to enter this chat.</p>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <% else %>
                  <% @room.messages.each do |message| %>
                    <%= render 'messages/message', message: message %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <br>
            <br>
            <div id="silent"></div>
            <% if @room.columndialogue %>
              <% if @room.users.exists?(current_user.id) %>
                <div class="chat-box">
                  <%= render 'messages/form', message: Message.new, room: @room %>
                </div>
              <% else %>
                <% if @room.users.uniq.count === 0 %>
                  <div class="chat-box">
                    <%= render 'messages/form', message: Message.new, room: @room %>
                  </div>
                <% else %>
                <% end %>
              <% end %>
            <% else %>
              <div class="chat-box">
                <%= render 'messages/form', message: Message.new, room: @room %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      
<% else %>
  <div class="d-flex align-items-center justify-content-center" style="height: 700px">
    <div class="container">
    
      <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <div class="row justify-content-md-center">
          <div class="col-xs-1 text-center">
            <br>
            <br>
            <%= link_to 'Sign in', sign_in_path, class: "btn btn-info btn-block" %>
            <br>
            <br>
            <h3 class="text-info">You can't chat if you're not signed in!</h3>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/search.html.erb
<h1>Success</h1>

<% @users.each do |user| %>
        <div class="card">
            <div class="card-body">
                <span class='name'><%= user.email %></span><br>
            </div>
        </div>
<% end %>